package by.freeseatsbybot;

public enum BotState {
    MAIN_MENU,
    AWAITING_CITY,
    AWAITING_DATE,
    AWAITING_TRAIN_CHOICE,
    AWAITING_TRAIN_NUMBER,
    AWAITING_DATE_AFTER_NUMBER,
    MONITORING
} 